spring.application.name=spring-boot-task2

spring.datasource.url=jdbc:h2:mem:cruddb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/book-realm

